SELECT
    ug.TITLE,
    ur.BOARD_ID,
    ur.REPLY_ID,
    ur.WRITER_ID,
    ur.CONTENTS,
    DATE_FORMAT(ur.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM
    USED_GOODS_REPLY AS ur
LEFT JOIN
    USED_GOODS_BOARD AS ug
ON
    ur.BOARD_ID = ug.BOARD_ID
WHERE
    DATE_FORMAT(ug.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY
    ur.CREATED_DATE, ug.TITLE;