SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS d
WHERE (d.SKILL_CODE & (SELECT code FROM SKILLCODES WHERE name='Python')) <> 0
   OR (d.SKILL_CODE & (SELECT code FROM SKILLCODES WHERE name='C#')) <> 0
ORDER BY ID ASC;
